% read bin file as generated by snSignalOutputBinary module

clear all
close all
clc

addpath('../helper_functions');

%% set parameters
files = { 'snacs_gps_and_channel_output.bin' };
length = 0.00005; % s
smpl_freq = 39e6;  %Hz
data_type = 'schar';

%% read file

files_n = size(files, 2);

samples = length * smpl_freq;

signals = zeros(files_n, samples);

for i = 1:files_n
    filename = cell2mat(files(i));
    signals(i, :) = read_snacs_bin_file(filename, samples, data_type);
end

%% plot
x_ax = 0:1/smpl_freq:length-1/smpl_freq;

figure;
hold on;
for i = 1:files_n
    switch i
        case 1
            color = 'b';
        case 2
            color = 'r';
        case 3
            color = 'g';
    end
    plot(x_ax, signals(i, :), [ color, '.-'] );
    grid on;
end
xlabel('Time [s]');
ylabel('Amplitude');
xlim([0, length]);
ylim([-10, 10]);

% save the figure:
save_figure_as_png('../../documentation/doxygen-sources/graphic/snacs-result_example08.png', 1024, 768);
